### ISSUE TITLE
naturally install latest plugin version

### ISSUE THREAD

**Issue by k2s** [roguePanda/aurelia-polymer#10]
command `jspm install github:roguePanda/aurelia-polymer` will install version 0.2.1
isn't it possible to change something (no idea what) so that it will install latest version ?

**Comment by bnavetta** [comment]
The current version is a beta, so JSPM doesn't install it by default. `jspm install aurelia-polymer --edge` should pull it in though.

**Comment by k2s** [comment]
good enough solution, thank you
