### ISSUE TITLE
Can't get the plugin to work

### ISSUE THREAD

**Issue by bobpardoe** [roguePanda/aurelia-polymer#11]
I have been following your doc at Aurelia to incorporate Polymer into the skeleton app.

I don't seem to be seeing the plugin being loaded i.e. there is no debug text saying it is being loaded.

Either because of this (or perhaps unrelated) I am not able to do 
<link rel="import" href="/bower_components/paper-drawer-panel/paper-drawer-panel.html"> ...

without errors relating to 'Cannot have text before the <template> tag showing up in the browser.

Any ideas please?

Also in your document you have single quotes around the jspm install 'aurelia-polymer@^1.0.0-beta' line. I worked it out in the end but a nooob might not be aware that the ' characters are not to be included in the jspm install text.

Thanks

Bob

**Comment by bnavetta** [comment]
Could you be more specific about what's happening and what your setup is? Also, the single quotes ought to be fine in a shell. In zsh at least, you'll get an error without them because `^` has a special meaning.

**Comment by bobpardoe** [comment]
Many thanks for the quick response.

Turns out that it was my fault. I was expecting the default value to be 
"main" in the bootstrapper but it is  "app", but of course you would 
know that ...



*Bob Pardoe*

M 	: 	07774 478876
T 	: 	01604 876909
A 	: 	NN4 6DN
E 	: 	bob@bobpardoe.com



If you are not the intended recipient, read no further. Close your eyes 
immediately and keep calm!
Trees were not harmed in the creation of this message.

**Comment by bnavetta** [comment]
No problem! Does it seem to be working now then?

**Comment by bnavetta** [comment]
Closing due to lack of response
