### ISSUE TITLE
Problems with aurelia-framework@1.0.0-beta.1.2.1

### ISSUE THREAD

**Issue by AndrzejT** [roguePanda/aurelia-polymer#15]
Do you plan to update your plugin for the new beta releases of aurelia?
Got this problem:

Uncaught (in promise) TypeError: aurelia.globalizeResources is not a function
    at r.configure (http://localhost:9001/jspm_packages/github/roguePanda/aurelia-polymer@0.2.1/index.js:11:13)
    at http://localhost:9001/jspm_packages/npm/aurelia-framework@1.0.0-beta.1.2.1/aurelia-framework.js:276:36
  configure 
  (anonymous function)

**Comment by bnavetta** [comment]
That's an older version of the plugin, so uninstalling it and running `jspm install aurelia-polymer --edge` ought to pull in the latest.
