### ISSUE TITLE
Cannot read property 'insertBefore' of null  at View.insertNodesBefore 

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [roguePanda/aurelia-polymer#20]
I got _Cannot read property 'insertBefore' of null  at View.insertNodesBefore_ error when I called aurelia.setRoot() and navigation menu in a _paper-tabs_ disappeared.

```
      <paper-tabs>
           <paper-tab link repeat.for="row of router.navigation" name.bind="row.config.name">
              <a href.bind="row.href" class="link" tabindex="-1" >${row.title}</a>
           </paper-tab>
    </paper-tabs>
```

Here is a workaround.
1. Apply this [patch](https://github.com/aurelia/templating/issues/259#issuecomment-209538915) to aurelia-templating.js.
2. Apply [this workaround](https://github.com/roguePanda/aurelia-polymer/issues/12#issue-144517499). That is, wrap _paper-tab_ within _div_.
3. Add [au-select](https://github.com/roguePanda/aurelia-polymer/issues/17#issuecomment-233112625) to _paper-tabs_.

```
      <paper-tabs au-select>
         <div>
           <paper-tab link repeat.for="row of router.navigation" name.bind="row.config.name">
              <a href.bind="row.href" class="link" tabindex="-1" >${row.title}</a>
           </paper-tab>
       </div>
    </paper-tabs>
```

Edit: 

The error can happen without setRoot().

There is another issue. The ${row.title} is rendered upper than I expected in a tab. This issue might be fixed by giving style.

You might need to add selectable like [this](https://github.com/roguePanda/aurelia-polymer/issues/17#issuecomment-233112625).

**Comment by bnavetta** [comment]
@HIRANO-Satoshi do you think this is an issue with aurelia/templating instead then?

**Comment by HIRANO-Satoshi** [comment]
Yes, I do.

Anyway, we are enjoying Aurelia and Polymer. :-)

**Comment by bnavetta** [comment]
Guess I'll close this then!
