### ISSUE TITLE
google-map-markers issue with repeat.for

### ISSUE THREAD

**Issue by ghost** [roguePanda/aurelia-polymer#21]
Hi,

I'm experiencing some trouble combining `repeat.for` and `google-map-marker`. By adding the marker manually, the HTML structure is as follows:

```
<google-map>
   <iron-selector>
      <google-map-marker></google-map-marker>
      <google-map-marker></google-map-marker>
      <google-map-marker></google-map-marker>
   </iron-selector>
</google-map>
```

But using `repeat.for`, it is like this:

```
<google-map>
   <iron-selector></iron-selector>
   <google-map-marker></google-map-marker>
   <google-map-marker></google-map-marker>
   <google-map-marker></google-map-marker>
</google-map>
```

and the marker is not present on the map...

Has anyone faced the same problem?

**Comment by bnavetta** [comment]
There have been a bunch of issues with `iron-selector` and `repeat.for` - see #17 for some more discussion. Basically, Aurelia wraps things in a `<template>` element, which `iron-selector` is written to ignore. @HIRANO-Satoshi found a workaround that might help

**Comment by bnavetta** [comment]
The `au-select` workaround attribute is in master now, could you give that a try?

**Comment by ghost** [comment]
@roguePanda Thanks for the answer! But due to project requirements we'd switched to ESRI maps...

**Comment by bnavetta** [comment]
No problem!
