### ISSUE TITLE
Why only listen to 'change' and 'notify' and not 'PROPNAME-changed'?

### ISSUE THREAD

**Issue by slundberg** [roguePanda/aurelia-polymer#22]
In the docs it appears as though any Polymer element property with `notify` set to `true` should be available for two-way data binding. However `polymer-aurelia` only listens to `change` and `notify` events. Which, while triggered on basic form elements (like `paper-input`) are not triggered for lots of other web components.

I added `PROPNAME-changed` to the list of events used by `polymer-aurelia` and things started working as expected. Should this be a PR?

**Comment by slundberg** [comment]
Any thoughts? I am happy to send a simple PR if it is helpful.

**Comment by bnavetta** [comment]
Sorry for the delay - must've gotten lost in my inbox.  I've been meaning to add some kind of configuration mechanism for other events, like the current hardcoded `IronSelectableBehavior` support, but if they follow a `PROPNAME-changed` pattern, even better. A PR would be incredibly helpful, thank you!

**Comment by slundberg** [comment]
So it looks like the compiled files are also in git and the build didn't work for me the first time around. So I'll just post the tiny change here instead:

index.js line 12 is currently

``` javascript
      propertyConfig[propName] = ['change', 'input'];
```

and should be

``` javascript
      propertyConfig[propName] = [propName+'-changed', 'input'];
```

to catch events from custom objects.

**Comment by bnavetta** [comment]
Just pushed a commit with the change, thanks! Yeah, committing built files like that isn't ideal, but I'm not sure how else to distribute ES6 libraries portably these days.

**Comment by slundberg** [comment]
Thanks!
