### ISSUE TITLE
Polymer 2.0 integration

### ISSUE THREAD

**Issue by avizcaino** [roguePanda/aurelia-polymer#28]
Hi!
This is not actually a bug report but more of an integration question (I already put it in [aurelia/templating](https://github.com/aurelia/templating/issues/502), but I guess this is the proper place).

I've been using Aurelia and Polymer together for the last year and I just been reading some of the Polymer 2.0 documentation and watching the Polymer Summit videos.

I was wondering if someone has already tested the Aurelia and Polymer 2.0 integration. I think it can be of a great use if you want to override some of the Polymer elements behavior/properties but actually I'm not quite grasping any more improvements over the Aurelia + Polymer 1 combination that I've been using till now.

A couple of months ago I was using a polymer-element that wasn't working as expected in some platforms and I had to fork the element code and override the problem with my own solution to solve the unexpected behavior. I think I could solve this now more easily now with Polymer 2, but I haven't tested yet.

Anyway, as I said, I was just wondering if someone has already tested it and if some of you can give some insight about the usefulness of this integration.

Thanks!

**Comment by bnavetta** [comment]
I haven't really been keeping up with Polymer 2.0, but if it uses the same registration hooks, then it ought to work!

**Comment by avizcaino** [comment]
Hi!
I've been trying to use Polymer 2.0 with this plugin but without any success... This is the error I'm getting:
<img width="782" alt="captura de pantalla 2017-02-24 a les 14 22 26" src="https://cloud.githubusercontent.com/assets/12660226/23304945/b36a2984-fa9c-11e6-9063-f44abfd08073.png">

I tried the same configuration with Polymer 1 and been able to run my app without any problem...

Anyone testing Polymer 2 integration?

**Comment by bnavetta** [comment]
I'm not using Aurelia or Polymer anymore, so I don't really know what's changed with Polymer 2 :/
