### ISSUE TITLE
Include AuSelectCustomAttribute in latest (beta) releases

### ISSUE THREAD

**Issue by ardean** [roguePanda/aurelia-polymer#30]
Can we integrate au-select in the latest (beta) releases?
I copy the source manually into my projects to make **paper-tabs** work. I'm using release **1.0.0-beta.1.0.3** because other versions (like the **master** branch) do not work in my aurelia projects.

Thank You

**Comment by bnavetta** [comment]
I can make a new GitHub release with the changes. Was there a particular issue you were having with the master branch?

**Comment by ardean** [comment]
The following error occurs when I try to use the master branch _(release v0.2.1, installed via jspm i aurelia-polymer)_:

![image](https://cloud.githubusercontent.com/assets/17138728/22455244/8388064c-e78b-11e6-83b2-3bcdf04b9bd1.png)

thank you for your support
