### ISSUE TITLE
Binding a value to a disabled paper-input does not work in Firefox

### ISSUE THREAD

**Issue by swiftanthony** [roguePanda/aurelia-polymer#5]
I have an issue with binding a value to paper-input in Firefox

The following code does not work:
`<paper-input disabled label="Email" value.bind="value"></paper-input>`

So does not:
`<paper-input disabled label="Email" value="${value}"></paper-input>`

If I use regular input element everything works as expected:
`<input disabled label="Email" value.bind="email" />`

**Comment by bnavetta** [comment]
Just out of curiosity, was it working in Chrome? There might be some underlying Firefox issue that's not specific to paper-input. Also, what about it wasn't working?

**Comment by swiftanthony** [comment]
Everything works in Chrome. 
Binding to a regular input element works in Firefox too.
But binding to paper-input results in "Unhandled promise rejection" error. 

From FF console:

`Unhandled promise rejection Object { result=2147549183,  name="NS_ERROR_UNEXPECTED",  filename="http://localhost:9000/lib/polymer/polymer.html.js",  more...}`

**Comment by bnavetta** [comment]
Looks like it's PolymerElements/iron-input#47. There's a patch for it, but I don't think it's been released yet.

**Comment by swiftanthony** [comment]
I see, thanks

**Comment by bnavetta** [comment]
Guess there isn't much we can do
