### ISSUE TITLE
how to use iron-list

### ISSUE THREAD

**Issue by k2s** [roguePanda/aurelia-polymer#7]
I am trying to use https://elements.polymer-project.org/elements/iron-list together with Aurelia component.

Binding of view property `items` to iron-list seams to work.
1. Problem I am facing is that repeated template is creating element `<aurelia-custom-component>` for each item, but is not initiating the component (constructor in aurelia-custom-component.js is not called).

``` html
<link rel="import" href="/lib/iron-list/iron-list.html">
<link rel="import" href="/lib/iron-image/iron-image.html">

<template>
  <require from="./aurelia-custom-component"></require>
  <iron-list items.bind="items" as="item">
    <template>
      <div>
        Works: [[item.title]]
        Works: <iron-image class="avatar" sizing="contain" src="[[item.url]]"></iron-image>

        Will not be rendered, only copied: <aurelia-custom-component></aurelia-custom-component>
      </div>
    </template>
  </iron-list>
</template>
```
1. iron-list is able to use "item" property withing Polymer templating like `[[item.title]]`, to pass this item to Aurelia component is another task which I don't know solution for.

**Comment by k2s** [comment]
I tried also more simple example with Polymer template repeater:

``` html
<template>
  <require from="./aurelia-custom-component"></require>
  <template is="dom-repeat" items.bind="items">
    <div># <span>{{index}}</span></div>
    <div>First name: <span>{{item.title}}</span></div>
    <aurelia-custom-component></aurelia-custom-component>
  </template>
</template>
```

The `<aurelia-custom-component>` tag is added to DOM for each item and looks like:

``` html
<aurelia-custom-component class="au-target" au-target-id="71"></aurelia-custom-component>
```

but Aurelia component is not 'started'.

**Comment by k2s** [comment]
My finding so far is that `document.createElement("aurelia-custom-component").constructor === HTMLElement` which means that my custom component is not registered with `document.registerElement`.

**Comment by k2s** [comment]
solution is on the way https://github.com/aurelia/web-components

**Comment by bnavetta** [comment]
Rather than mixing binding systems, it might be easier to just stick with Aurelia templating and use something like [`aurelia-ui-virtualization`](https://github.com/aurelia/ui-virtualization). For now, I think you're right about Aurelia custom components not using `document.registerElement`

**Comment by bnavetta** [comment]
@k2s are you fine if I close this given the alternatives?
