### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by k2s** [roguePanda/aurelia-polymer#9]
README.md seams to be outdated
is there a reason why this [document](https://gist.github.com/roguePanda/3a0854de9c71dfac3ff8) is not part of readme or doc folder ?

thank you for this plugin

**Comment by bnavetta** [comment]
I'd generally suggest the [documentation article](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.3/doc/article/integrating-with-polymer), but the README should probably link to it
